name: Build and publish SDK package

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted # ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: npm-package-tag
        name: Determine tag for package
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            NPM_TAG="nightly"
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            NPM_TAG="next"
          elif [[ $GITHUB_REF == refs/tags/v*-* ]]; then
            NPM_TAG=next
          elif [[ $GITHUB_REF == refs/tags/v* ]]; then
            NPM_TAG=latest
          fi
          echo "NPM_TAG=${NPM_TAG}" >> $GITHUB_ENV
          echo "npm_tag=${NPM_TAG}" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          registry-url: 'https://npm.pkg.github.com'
          scope: '@momentum-xyz'
      - id: npm-deps
        name: Install dependencies
        run: npm ci --ignore-scripts
      - id: build
        name: NPM build
        run: npm run build
      - id: publish
        name: Publish NPM package
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --tag "${{ steps.npm-package-tag.outputs.npm_tag }}"
